# Generated by Django 4.2.25 on 2026-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="linked_api_projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="performance_projects",
                to="projects.project",
                verbose_name="关联的接口项目",
            ),
        ),
    ]
