# Generated by Django 4.2.25 on 2026-04-11 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_projectthirdpartyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('project', 'Project'), ('api', 'API Testing'), ('web', 'Web Testing'), ('app', 'App Testing'), ('perf', 'Performance Testing')], max_length=32, unique=True, verbose_name='module')),
                ('menu_items', models.JSONField(default=list, verbose_name='menu items')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'workspace menu config',
                'verbose_name_plural': 'workspace menu configs',
                'db_table': 'workspace_menu_configs',
            },
        ),
    ]
