# Generated by Django 4.2.25 on 2026-04-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_workspace_menu_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sonic_project_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="sonic project id"
            ),
        ),
    ]
