# Generated by Django 4.2.25 on 2026-04-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_sonic_project_id"),
        ("scheduled_tasks", "0007_notice_targets_to_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="app_run_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="可选 JSON，如 device_udid、device_id、device_name、platform（供展示或后续扩展）",
                verbose_name="App 执行配置",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.environment",
                verbose_name="执行环境",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="suite_ids",
            field=models.JSONField(
                default=list,
                help_text="存储多个测试套件ID的JSON数组（App 类型为 Sonic 测试套件 id）",
                verbose_name="测试套件ID列表",
            ),
        ),
    ]
